In [ ]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (2.3.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting pydantic<3,>=2 (from ydata-profiling)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2.4,>=1.22 (from ydata-profiling)
  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in d:\udemy\datascience\python\venv\lib\site-packages (from ydata-profiling) (0.14.6)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.5-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Using cached numba-0.62.1-cp313-cp313-win_amd64.whl.metadata (2.9 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp313-cp313-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in d:\udemy\datascience\python\venv\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\udemy\datascience\python\venv\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\udemy\datascience\python\venv\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Using cached llvmlite-0.45.1-cp313-cp313-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in d:\udemy\datascience\python\venv\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\udemy\datascience\python\venv\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in d:\udemy\datascience\python\venv\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2->ydata-profiling)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3,>=2->ydata-profiling)
  Using cached pydantic_core-2.41.5-cp313-cp313-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in d:\udemy\datascience\python\venv\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=2->ydata-profiling)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\udemy\datascience\python\venv\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\udemy\datascience\python\venv\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\udemy\datascience\python\venv\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\udemy\datascience\python\venv\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.11.12)
Requirement already satisfied: patsy>=0.5.6 in d:\udemy\datascience\python\venv\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in d:\udemy\datascience\python\venv\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in d:\udemy\datascience\python\venv\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in d:\udemy\datascience\python\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 2.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.0 MB 2.7 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.0 MB 2.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.0 MB 2.7 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.0 MB 2.7 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.0 MB 2.7 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.0 MB 2.7 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.0 MB 2.7 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.0 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 6.0/8.0 MB 2.7 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 2.6 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 2.6 MB/s  0:00:03
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 2.6 MB/s eta 0:00:01
   --------------- ------------------------ 1.0/2.7 MB 2.6 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.7 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 2.4 MB/s  0:00:01
Downloading llvmlite-0.45.1-cp313-cp313-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
    --------------------------------------- 0.5/38.1 MB 2.9 MB/s eta 0:00:13
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.0/38.1 MB 2.6 MB/s eta 0:00:15
   - -------------------------------------- 1.3/38.1 MB 146.9 kB/s eta 0:04:11
   - -------------------------------------- 1.8/38.1 MB 213.7 kB/s eta 0:02:50
   -- ------------------------------------- 2.4/38.1 MB 277.3 kB/s eta 0:02:10
   --- ------------------------------------ 2.9/38.1 MB 337.6 kB/s eta 0:01:45
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.1/38.1 MB 366.5 kB/s eta 0:01:36
   --- ------------------------------------ 3.7/38.1 MB 299.9 kB/s eta 0:01:55
   ---- ----------------------------------- 4.2/38.1 MB 340.3 kB/s eta 0:01:40
   ---- ----------------------------------- 4.7/38.1 MB 377.4 kB/s eta 0:01:29
   ----- ---------------------------------- 5.2/38.1 MB 414.9 kB/s eta 0:01:20
   ----- ---------------------------------- 5.2/38.1 MB 414.9 kB/s eta 0:01:20
   ----- ---------------------------------- 5.2/38.1 MB 414.9 kB/s eta 0:01:20
   ----- ---------------------------------- 5.2/38.1 MB 414.9 kB/s eta 0:01:20
   ----- ---------------------------------- 5.2/38.1 MB 414.9 kB/s eta 0:01:20
   ----- ---------------------------------- 5.5/38.1 MB 400.0 kB/s eta 0:01:22
   ------ --------------------------------- 6.0/38.1 MB 433.3 kB/s eta 0:01:15
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.3/38.1 MB 449.9 kB/s eta 0:01:11
   ------ --------------------------------- 6.6/38.1 MB 363.2 kB/s eta 0:01:27
   ------- -------------------------------- 7.1/38.1 MB 389.1 kB/s eta 0:01:20
   -------- ------------------------------- 7.9/38.1 MB 426.9 kB/s eta 0:01:11
   -------- ------------------------------- 8.4/38.1 MB 451.2 kB/s eta 0:01:06
   --------- ------------------------------ 8.7/38.1 MB 461.6 kB/s eta 0:01:04
   --------- ------------------------------ 9.4/38.1 MB 497.3 kB/s eta 0:00:58
   ---------- ----------------------------- 9.7/38.1 MB 506.8 kB/s eta 0:00:57
   ---------- ----------------------------- 10.2/38.1 MB 529.5 kB/s eta 0:00:53
   ----------- ---------------------------- 11.0/38.1 MB 562.6 kB/s eta 0:00:49
   ------------ --------------------------- 11.5/38.1 MB 584.2 kB/s eta 0:00:46
   ------------ --------------------------- 12.1/38.1 MB 604.6 kB/s eta 0:00:44
   ------------- -------------------------- 12.6/38.1 MB 625.4 kB/s eta 0:00:41
   ------------- -------------------------- 13.1/38.1 MB 645.5 kB/s eta 0:00:39
   -------------- ------------------------- 13.6/38.1 MB 665.4 kB/s eta 0:00:37
   --------------- ------------------------ 14.4/38.1 MB 694.3 kB/s eta 0:00:35
   --------------- ------------------------ 14.7/38.1 MB 703.8 kB/s eta 0:00:34
   --------------- ------------------------ 14.9/38.1 MB 705.9 kB/s eta 0:00:33
   ---------------- ----------------------- 15.5/38.1 MB 724.0 kB/s eta 0:00:32
   ---------------- ----------------------- 15.7/38.1 MB 733.2 kB/s eta 0:00:31
   ---------------- ----------------------- 16.0/38.1 MB 734.0 kB/s eta 0:00:31
   ----------------- ---------------------- 16.5/38.1 MB 751.6 kB/s eta 0:00:29
   ----------------- ---------------------- 16.8/38.1 MB 760.1 kB/s eta 0:00:29
   ----------------- ---------------------- 16.8/38.1 MB 760.1 kB/s eta 0:00:29
   ------------------ --------------------- 17.3/38.1 MB 764.1 kB/s eta 0:00:28
   ------------------ --------------------- 17.8/38.1 MB 780.3 kB/s eta 0:00:27
   ------------------ --------------------- 17.8/38.1 MB 780.3 kB/s eta 0:00:27
   ------------------ --------------------- 17.8/38.1 MB 780.3 kB/s eta 0:00:27
   ------------------- -------------------- 18.4/38.1 MB 782.7 kB/s eta 0:00:26
   ------------------- -------------------- 18.9/38.1 MB 798.0 kB/s eta 0:00:25
   -------------------- ------------------- 19.1/38.1 MB 801.9 kB/s eta 0:00:24
   -------------------- ------------------- 19.7/38.1 MB 817.5 kB/s eta 0:00:23
   --------------------- ------------------ 20.2/38.1 MB 832.6 kB/s eta 0:00:22
   --------------------- ------------------ 21.0/38.1 MB 854.8 kB/s eta 0:00:21
   --------------------- ------------------ 21.0/38.1 MB 854.8 kB/s eta 0:00:21
   --------------------- ------------------ 21.0/38.1 MB 854.8 kB/s eta 0:00:21
   ---------------------- ----------------- 21.5/38.1 MB 853.9 kB/s eta 0:00:20
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19
   ----------------------- ---------------- 22.0/38.1 MB 868.5 kB/s eta 0:00:19

In [1]:
from ydata_profiling import ProfileReport
import pandas as pd

dataset=pd.read_excel('flight_price.xlsx')

In [2]:
dataset

           Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
0           IndiGo      24/03/2019  Banglore  ...    non-stop         No info   3897
1        Air India       1/05/2019   Kolkata  ...     2 stops         No info   7662
2      Jet Airways       9/06/2019     Delhi  ...     2 stops         No info  13882
3           IndiGo      12/05/2019   Kolkata  ...      1 stop         No info   6218
4           IndiGo      01/03/2019  Banglore  ...      1 stop         No info  13302
...            ...             ...       ...  ...         ...             ...    ...
10678     Air Asia       9/04/2019   Kolkata  ...    non-stop         No info   4107
10679    Air India      27/04/2019   Kolkata  ...    non-stop         No info   4145
10680  Jet Airways      27/04/2019  Banglore  ...    non-stop         No info   7229
10681      Vistara      01/03/2019  Banglore  ...    non-stop         No info  12648
10682    Air India       9/05/2019     Delhi  ...     2 stops         No info  11753

[10683 rows x 11 columns]

In [3]:
report=ProfileReport(dataset,title='Flight Data Report')

In [7]:
report.to_file('report.html')

Export report to file: 100%|██████████| 1/1 [00:00<00:00, 108.81it/s]

In [9]:
!pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in d:\udemy\datascience\python\venv\lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in d:\udemy\datascience\python\venv\lib\site-packages (from ipywidgets) (9.8.0)
Requirement already satisfied: traitlets>=4.3.1 in d:\udemy\datascience\python\venv\lib\site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: colorama>=0.4.4 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in d:\udemy\datascience\python\venv\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in d:\udemy\datascience\python\venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in d:\udemy\datascience\python\venv\lib\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in d:\udemy\datascience\python\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in d:\udemy\datascience\python\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in d:\udemy\datascience\python\venv\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/914.9 kB ? eta -:--:--
   ---------------------------------- ----- 786.4/914.9 kB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 914.9/914.9 kB 1.6 MB/s  0:00:00
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 891.8 kB/s eta 0:00:02
   --------- ------------------------------ 0.5/2.2 MB 891.8 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.2 MB 733.7 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.2 MB 738.6 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.2 MB 738.6 kB/s eta 0:00:02
   ----------------------- ---------------- 1.3/2.2 MB 718.2 kB/s eta 0:00:02
   ----------------------- ---------------- 1.3/2.2 MB 718.2 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 663.3 kB/s eta 0:00:01
   ---------------------------- ----------- 1.6/2.2 MB 663.3 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 662.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 662.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 662.2 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 609.7 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 609.7 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 566.0 kB/s  0:00:03
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets

   ---------------------------------------- 0/3 [widgetsnbextension]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   ---------------------------------------- 3/3 [ipywidgets]

Successfully installed ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15

In [11]:
report.to_notebook_iframe()

In [12]:
df=pd.read_csv('cleaned_dataset.csv')
df.head()

   Total_Stops  Price  ...  Additional_Info_No info  Additional_Info_Red-eye flight
0            0   3897  ...                      1.0                             0.0
1            2   7662  ...                      1.0                             0.0
2            2  13882  ...                      1.0                             0.0
3            1   6218  ...                      1.0                             0.0
4            1  13302  ...                      1.0                             0.0

[5 rows x 44 columns]

In [13]:
clean_report=ProfileReport(df,title='Cleaned Flight Data')
clean_report.to_notebook_iframe()

100%|██████████| 44/44 [00:01<00:00, 43.71it/s]1<00:00, 35.77it/s, Describe variable: Additional_Info_Red-eye flight]
Summarize dataset: 100%|██████████| 117/117 [00:17<00:00,  6.62it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:08<00:00,  8.79s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]