In [69]:
# Import all the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [70]:
# Load the dataset
wine_data_path = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv"
dataset = pd.read_csv(wine_data_path)
dataset.head(5)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [71]:
dataset.sample(5)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1812,white,5.6,0.46,0.24,4.80,0.042,24.0,72.0,0.99080,3.29,0.37,12.6,6
1982,white,7.6,0.20,0.30,14.20,0.056,53.0,212.5,0.99900,3.14,0.46,8.9,8
3321,white,6.0,0.26,0.33,4.35,0.040,15.0,80.0,0.98934,3.29,0.50,12.7,6
4772,white,6.4,0.28,0.45,8.60,0.057,47.0,223.0,0.99654,3.16,0.51,9.1,5
698,white,7.5,0.31,0.51,14.80,0.039,62.0,204.0,0.99820,3.06,0.60,9.5,5

In [72]:
dataset.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6487.000000,6489.000000,6494.000000,6495.000000,6495.000000,6497.000000,6497.000000,6497.000000,6488.000000,6493.000000,6497.000000,6497.000000
mean,7.216579,0.339691,0.318722,5.444326,0.056042,30.525319,115.744574,0.994697,3.218395,0.531215,10.491801,5.818378
std,1.296750,0.164649,0.145265,4.758125,0.035036,17.749400,56.521855,0.002999,0.160748,0.148814,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [73]:
dataset.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [74]:
dataset.duplicated().sum()

np.int64(1168)

In [ ]:
# Preprocessing The Dataaaaaaa

#Drop Null/na values and duplicatessss
print(dataset.shape)
dataset=dataset.dropna()
dataset=dataset.drop_duplicates()

(6497, 13)

In [76]:
print(dataset.shape)

(5295, 13)

In [77]:
dataset.sample(5)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3032,white,6.7,0.14,0.46,1.60,0.036,15.0,92.0,0.99264,3.37,0.49,10.9,5
5329,red,7.8,0.55,0.35,2.20,0.074,21.0,66.0,0.99740,3.25,0.56,9.2,5
1772,white,7.8,0.40,0.26,9.50,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,6
3651,white,6.3,0.32,0.17,17.75,0.060,51.0,190.0,0.99916,3.13,0.48,8.8,6
2579,white,6.4,0.28,0.56,1.70,0.156,49.0,106.0,0.99354,3.10,0.37,9.2,6

In [78]:
# Now Split the data
X=dataset.iloc[:,1:len(dataset.columns)]
y=dataset.iloc[:,0]

In [79]:
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
6490,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6491,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6492,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6495,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [80]:
y

0       white
1       white
2       white
3       white
6       white
        ...
6490      red
6491      red
6492      red
6495      red
6496      red
Name: type, Length: 5295, dtype: object

In [81]:
# Split the dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [82]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
259,5.8,0.36,0.38,0.9,0.037,3.0,75.0,0.99040,3.28,0.34,11.400000,4
1327,6.8,0.26,0.33,1.5,0.047,44.0,167.0,0.99280,3.12,0.44,10.500000,6
5117,7.8,0.53,0.33,2.4,0.080,24.0,144.0,0.99655,3.30,0.60,9.500000,5
826,6.8,0.25,0.38,8.1,0.046,24.0,155.0,0.99560,3.33,0.59,10.200000,6
689,6.7,0.17,0.37,2.0,0.039,34.0,125.0,0.99220,3.26,0.60,10.800000,7
...,...,...,...,...,...,...,...,...,...,...,...,...
3830,4.8,0.26,0.23,10.6,0.034,23.0,111.0,0.99274,3.46,0.28,11.500000,7
4699,6.8,0.30,0.33,12.8,0.041,60.0,168.0,0.99659,3.10,0.56,9.800000,5
6373,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7
6414,6.1,0.32,0.25,2.3,0.071,23.0,58.0,0.99633,3.42,0.97,10.600000,5
1038,7.1,0.15,0.34,5.3,0.034,33.0,104.0,0.99530,3.37,0.52,9.300000,7

In [83]:
y_test

516     white
1320    white
983     white
4380    white
6362      red
        ...
4576    white
1275    white
1019    white
3771    white
3102    white
Name: type, Length: 1324, dtype: object

# Accuracy without PCA

In [84]:
# Standardize the Values
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

# Now Lets Train the model and check the accuracy
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_predicted=knn.predict(X_test)
print('accuracy_score:',accuracy_score(y_pred=y_predicted,y_true=y_test)*100)

accuracy_score: 99.39577039274926

# Accuracy With PCA

In [85]:
# Standardize the Values
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

# Apply PCA
pca=PCA(n_components=5)
X_train_pca=pca.fit_transform(X_train_scaled)
X_test_pca=pca.transform(X_test_scaled)

# Now Lets Train the model and check the accuracy
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_pca,y_train)
y_predicted_pca=knn.predict(X_test_pca)
print('accuracy_score:',accuracy_score(y_pred=y_predicted_pca,y_true=y_test)*100)

accuracy_score: 99.09365558912387

In [86]:
X_train_pca

array([[-0.24994863, -1.65852284, -0.75686742, -2.30968738, -0.91217965],
       [ 1.3814054 , -0.3011962 ,  0.17595952, -0.37669106, -0.84728903],
       [-1.37212304,  1.09467319, -0.60293653, -0.07844436, -0.70259436],
       ...,
       [-1.17795764, -3.4626445 , -0.99893956,  2.65313488,  0.35599172],
       [-1.9983349 , -0.26255176, -0.68819829,  1.74787413, -1.02972782],
       [ 0.68404557, -0.07273753,  0.08518942,  0.97709833,  0.56184381]],
      shape=(3971, 5))

In [87]:
# Implementation Using pipeline
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=5)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

print(accuracy_score(y_test, y_pred) * 100)

99.09365558912387