In [97]:
!pip install bs4

Requirement already satisfied: bs4 in c:\users\sambhav_surthi\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sambhav_surthi\anaconda3\lib\site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\sambhav_surthi\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.5)

In [98]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\sambhav_surthi\anaconda3\lib\site-packages (5.3.0)

In [2]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.tokenize import sent_tokenize,word_tokenize
from numba.cpython.setobj import set_ne
from sklearn.model_selection import train_test_split
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from nltk.corpus import stopwords
import gensim
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess

from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

from bs4 import BeautifulSoup
from sklearn.metrics import classification_report,accuracy_score

In [3]:
dataset=pd.read_csv('../dataset/kindle_review.csv')

In [4]:
dataset

,index,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000
...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,2183,B001DUGORO,"[0, 0]",4,Valentine cupid is a vampire- Jena and Ian ano...,"02 28, 2014",A1OKS5Q1HD8WQC,lisa jon jung,jena,1393545600
11996,11996,6272,B002JCSFSQ,"[2, 2]",5,I have read all seven books in this series. Ap...,"05 16, 2011",AQRSPXLNEQAMA,TerryLP,Peacekeepers Series,1305504000
11997,11997,12483,B0035N1V7K,"[0, 1]",3,This book really just wasn't my cuppa. The si...,"07 26, 2013",A2T5QLT5VXOJAK,hwilson,a little creepy,1374796800
11998,11998,3640,B001W1XT40,"[1, 2]",1,"tried to use it to charge my kindle, it didn't...","09 17, 2013",A28MHD2DDY6DXB,"Allison A. Slater ""Gryphon50""",didn't work,1379376000
11999,11999,11398,B003370JUS,"[5, 6]",3,Taking Instruction is a look into the often hi...,"07 5, 2012",A3JUXLB4K9ZXCC,Dafna Yee,"If you like BDSM with a touch of romance, this...",1341446400

In [5]:
dataset.columns

Index(['index', 'Unnamed: 0', 'asin', 'helpful', 'rating', 'reviewText',
       'reviewTime', 'reviewerID', 'reviewerName', 'summary',
       'unixReviewTime'],
      dtype='object')

In [6]:
dataset=dataset.drop(columns=['index', 'Unnamed: 0', 'asin','reviewTime', 'reviewerID','unixReviewTime','reviewerName','helpful','summary'],axis=1)

In [7]:
dataset

       rating                                         reviewText
0           3  Jace Rankin may be short, but he's nothing to ...
1           5  Great short read.  I didn't want to put it dow...
2           3  I'll start by saying this is the first of four...
3           3  Aggie is Angela Lansbury who carries pocketboo...
4           4  I did not expect this type of book to be in li...
...       ...                                                ...
11995       4  Valentine cupid is a vampire- Jena and Ian ano...
11996       5  I have read all seven books in this series. Ap...
11997       3  This book really just wasn't my cuppa.  The si...
11998       1  tried to use it to charge my kindle, it didn't...
11999       3  Taking Instruction is a look into the often hi...

[12000 rows x 2 columns]

In [8]:
dataset['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [9]:
def fixRating(rating):
    if rating <=3:
        return 0
    else:
        return 1

In [10]:
dataset['sentiment']=dataset['rating'].apply(fixRating)

In [11]:
dataset

       rating                                         reviewText  sentiment
0           3  Jace Rankin may be short, but he's nothing to ...          0
1           5  Great short read.  I didn't want to put it dow...          1
2           3  I'll start by saying this is the first of four...          0
3           3  Aggie is Angela Lansbury who carries pocketboo...          0
4           4  I did not expect this type of book to be in li...          1
...       ...                                                ...        ...
11995       4  Valentine cupid is a vampire- Jena and Ian ano...          1
11996       5  I have read all seven books in this series. Ap...          1
11997       3  This book really just wasn't my cuppa.  The si...          0
11998       1  tried to use it to charge my kindle, it didn't...          0
11999       3  Taking Instruction is a look into the often hi...          0

[12000 rows x 3 columns]

In [12]:
dataset['sentiment'].value_counts()

sentiment
0    6000
1    6000
Name: count, dtype: int64

In [13]:
# Dataset is fixed Now we need to preprocess the text
sentences=[]

for elements in dataset['reviewText']:
    sent=sent_tokenize(elements.lower())
    sentences.append(sent)

In [14]:
sentences

[["jace rankin may be short, but he's nothing to mess with, as the man who was just hauled out of the saloon by the undertaker knows now.",
  "he's a famous bounty hunter in oregon in the 1890s who, when he shot the man in the saloon, just finished a years long quest to avenge his sister's murder and is now trying to figure out what to do next.",
  'when the snotty-nosed farm boy he just rescued from a gang of bullies offers him money to kill a man who forced him off his ranch, he reluctantly agrees to bring the man to justice, but not to kill him outright.',
  'but, first he needs to tell his sister\'s widower the news.kyla "kyle" springer bailey has been riding the trails and sleeping on the ground for the past month while trying to find jace.',
  "she wants revenge on the man who killed her husband and took her ranch, amongst other crimes, and she's not so keen on the detour jace wants to take.",
  "but she realizes she's out of options, so she hides behind her boy persona as best she can and tries to keep pace.",
  "when a confrontation along the way gets her shot and jace discovers that kyle's a kyla, she has to come clean about the *whole* reason she needs this scoundrel dead and hope he'll still help her.the book has its share of touching moments and slow-blooming romance.",
  "kyla, we find out, has good reason to fear men and hide behind a boy's persona.",
  'watching jace slowly pull her out of that shell and help her conquer her fears was endearing.',
  "her pain was real and deeply-rooted and didn't just disappear in the face of his sexiness.",
  'neither did his understandable aversion to marriage magically disappear after a round of nookie.',
  "why would a man who's drifted from town to town for his entire adult life - a man who's killed his fair share of men along the way - feel he'd make a good husband or father?",
  "they're both the walking wounded and in a unique position to help each other, they just need time to realize it.however, while it was packed to bursting with my favorite themes - old west setting, a heroine passing as male, a morally ambiguous hero, wounded souls, road romance, the kitchen sink - there was a certain...distance in the writing that kept me from getting carried away.",
  "both characters were distinct and fully-formed and i couldn't point to any glaring instances of bland telling or anything, i just never felt really invested.",
  'i enjoyed it quite a bit, as it was an exciting trip, but i was watching them from far away.',
  "i definitely wasn't on the run alongside them.",
  "add on a hasty and too tidy ending, and the book left me feeling a bit less than completely satisfied.i enjoyed the book, but i can't say it was above average.",
  "i'd still read another book by the author.note: i read the re-released ebook version and noticed there were a lot of formatting errors and missing words.",
  'i had to mentally edit as i read for some sentences to make sense.',
  "it wasn't too too bad, but it was a little distracting."],
 ['great short read.',
  "i didn't want to put it down so i read it all in one sitting.",
  'the sex scenes were great between the two males and one female character...a bit surprising - i never thought you could do that!',
  'i learned something new and really enjoyed reading this book!',
  'this is a great way to get all hot and bothered and take advantage of your significant other(s)!'],
 ["i'll start by saying this is the first of four books so i wasn't expecting it to &#34;conclude&#34;.",
  "it centers on 3 children, alex and his younger brother argus, and alex's friend, sapphire.",
  "they find a name on a bus map that they can't find and so the mystery starts.",
  "well written with good character development although lots of room still for more.it's quite a short book so i will be moving onto book 2 swiftly."],
 ['aggie is angela lansbury who carries pocketbooks instead of writing them.',
  'while this light murder mystery is laced with misdirections, the clues lead to a rather obvious cliche of an ending.',
  'the setting,  views described in the story are its best and most believable parts, and aggie the only well-written character.',
  'very light reading.'],
 ['i did not expect this type of book to be in library was pleased to find it price was right'],
 ['aislinn is a little girl with big dreams.',
  'after the death of her older brother, she decides to follow in his footsteps and become a lady knight.',
  'her quest for knighthood brings many challenges and the temptation of forbidden love.',
  'aislinn learns that being a knight means putting the kingdom in front of personal concerns and helping those that cannot help themselves.',
  'in a journey is fraught with danger and filled with adventure, aislinn is forced to grow up fast.',
  'she must stay strong and develop the skills necessary to realize her lifelong dream.with sword fights, passionate love, mythical creatures, and courtly games, woman of honor is my kind of book.',
  "i love the idea of incorporating real history in fantasy, and ms. zoltack's book is based on the real life story of a group of female knights.",
  'blending history with fiction, her writing is full of plot and adventure and her characters are strong and believable.',
  'most of all, i grew to love all of them and cared about their hardships and successes.aislinn is quite the main protagonist.',
  "she's tenacious and bold, beautiful and strong.",
  'the romance that blooms between her and the prince is well developed after years of solid friendship and teasing.',
  'i enjoyed reading about their secret courtship and had no idea how their romance would turn out!',
  'ms. zoltack has a few twists in store that will shock and startle as well as please.in conclusion, i thoroughly recommend this book for everyone that enjoys fantasy, romance and adventure!',
  'i will be eagerly awaiting the sequel, knight of glory.'],
 ['this has the makings of a good story... unfortunately it disappoints.it tells of two alpha were who are members of unfriendly packs... they have grown up together with one being gay and the other straight... then when it seems they are about to get together something happens and the story is told in alternating chapters of past and present.. the story and the couple fall apart in the switch of time and lack of a sustainable reason for the break.'],
 ['i got this because i like collaborated short stories.',
  'alot of times when two good writers put their heads together, the results turn out well.',
  'this is the case with this short story.',
  'the writers take an age old lesson and turn it into a good read.',
  'it begins with, as they call it, crazy #1 who is picking up a hitchhiker and from there it gets graphic and a little much for my taste.',
  'then it cuts to nutcase #2 who is hitchhiking.',
  'they inevitably get together and the results are suspenseful.',
  'the ending i felt was well deserved on both accounts.i also watched the video of the two authors on how they decided to break this short story up and the idea was cool.',
  'one wrote their side for scenario 1 and the other did scenario 2 without talking with each other about how tier side was going.',
  'then, when it came for them to bring the two pieces together, they made them fit perfectly.',
  "i think it took great talent for two authors to take their two seperate stories and merge them as well as they did.the story does have some pretty graphic details which is forwarned, but if you don't mind a little detail for a short story, then definitely pick this one up."],
 ['loved this book, i am hooked on this series and hope there is more!',
  "kelsey maxwell really made these characters so i couldn't get enough."],
 ["and that's a good thing.",
  'short, sweet tease that gives you everything in a quick kick.',
  'a kick that comes in the dark.'],
 ['i received a copy of book to review.',
  '"a secret society.',
  'a fanatical cult.',
  'a telepathic girl."',
  'are not my cup of tea.',
  "this was not what i expected and i really don't need another continuational book.",
  "i still haven't read the catching fire from the hunger games.",
  "i don't get into all this sci-fi stuff.",
  'just not my cup of tea.',
  'sorry.'],
 ['even though you already know what the outcome will be, this is still an enjoyable and erotic read.',
  'it was just a little short for my taste.'],
 ['i read the other reviews and decided to give it a try despite the review labeling it brutal.',
  'believe the reviewer who called it brutal.',
  'this was beyond disturbing.',
  'i can read almost anything recognizing that it is fiction but not this.',
  'i returned it.',
  'if less than a 1 star rating were available i would have used it.'],
 ['i just finished a re-read of wicked garden and all i can say is wow!!',
  '!, even in a novella lorelei james can write stories so hot your e-reader starts smokin!wicked garden is a short story about lost loves reuniting with a little extra sumthin, sumthin.',
  'billy buchanan returns to spearfish as a favor for a business associate.',
  'he agreed as a favor but also because it would give him a chance to re-ignite the spark from his high school flame eden lacroix.',
  'for the past ten years he has regretted walking away from eden.',
  'eden has spent the last ten years building a career and dedicated to the local community center helping at risk kids.',
  "she hasn't had time for real relationships, just the occasional no strings attached hook ups with sexy native american rock star jon white feather.when billy and eden see each other for the first time in ten years the chemistry spikes off the charts but eden is determined to fight it because billy is working on a project that could destroy her job.",
  'he quickly sweet talks her into seeing him out side the project.',
  'as things heat up between eden and billy and they are both realizing they still have strong feelings for each other...dunh dunh dunh....jon comes home for a couple of days.',
  'billy and jon decide they want to give eden one of her darkest fantasies.',
  'boy o boy is this a hot menage!i really like eden, even though she is worried about her heart and billy leaving her again, she takes charge of her sexuality and is not scared to go after what she wants sexually.',
  'as much as i liked eden in this story, it is billy and jon who stole the story for me.',
  'both men are sexy and strong.',
  'billy is possessive, sexy, dominant and vulnerable, i absolutely adore the way he treats eden and some of the insecurities he displays.',
  "jon...oh my, he is my favorite, don't get me wrong i love billy, but the way jon treats eden before, during and after the menage just melts my heart (among other things), not to mention jon is a sexy rock star.",
  'i am over the moon excited that jon is getting his own novella ballroom blitz, release date 10/2/12.folks...let me tell you...if i could get the action that went on in the work out room in wicked garden i would be in the work out room five to ten times a day!wicked garden is a great novella perfect for an afternoon when you want to escape for a few hours.',
  'a bonus is we get to see how sexy lorelei writes non-cowboys, yep be it in a cowboy hat or a suit  ms. james knows how to write sexy as hell heroes!'],
 ["but it's from the king james version, so far as i can tell.",
  'as you may know, from 1611, the kjv was published with these books included.',
  "you can get an ebook kjv with apocrypha from kindle.bible (kjv with apocrypha) (best navigation with direct verse jump)orking james bible with the apocryphaorking james bible with the apocryphafor those who want to read more commentary on these books than is provided in the short intros by misbach, you can refer to either halley's bible handbookhalley's bible handbook with the new international version---deluxe editionor the new unger's bible handbookthe new unger's bible handbook, both available as kindle ebooks."],
 ['i was very disappointed with this book... not because i have anything against blonds (i am one), but because i figured that out of 500 jokes, there had to be some good laughs.',
  'i was wrong.',
  "first, i didn't count them, but i'd be real surprised if there were even 200 jokes in this book.",
  'second, among those 200 possible jokes, at least 50 were repeated 2 or more time in different parts of the book.',
  "it's almost as if the writer kept a running list of jokes as he heard them, with no real concern about whether or not they might already have been recorded.",
  'then he decided there must be at least 500 jokes here.',
  'finally, to be perfectly frank with you, i do not recall laughing at a single one of these "jokes".',
  'most were better described as insults, mistaking the degradation of a group of people for humor.',
  'very "7th grade" material.',
  "don't bother with this one.",
  "it's not worth the 99 cents.",
  'it\'s not even worth "free".'],
 ['this was a super quick book.',
  'i wish it would have been longer.',
  'really liked the characters.',
  'very sexy bedroom, pool table sex.',
  'this is a good author.'],
 ['how many times is author going to get amazon to delete this or add comments about alleged conspiracies of people out to get him?',
  'is he f*in delusional?',
  'my review:i have to agree with a few previous reviewers.',
  "the author doesn't know the basic mechanics of writing, so how in the world is this or any other he's written full stars?",
  "there's not a page that isn't filled with grammar problems.",
  "the story itself suffers the same problems from the author's inattention to detail.",
  'characters are inconsistent in their actions.',
  "it's like they're interchangeable pegs on a board the author puts into places when he needs them."],
 ['i love j.r. wards books.',
  'this story was completely awsome zsadist is by for my favorite in the series.'],
 ['this was my first with this author.',
  'i thoroughly enjoyed it.i have to say the concept of dragon, elves and djinn being at war is new to me.',
  'theres usually a truce in place.',
  'that elves and djinn team up to eliminate dragon mates, in an attempt to wipe out the dragon race was refreshing to read.',
  'story wise i mean.scarlet is a pop star.',
  'she has been in hiding for 7 years.janos is a dragon.',
  'he is also an elder.scarlet is his mate.',
  'janos must protect her till he can impregnate her.',
  'once that is accomplished he can change her thus giving her a way to protect herself.the story was too short.',
  'only 90 pages.',
  'still a lot was told in such a short space.',
  'looking forward to continuing the saga in the next book.'],
 ['this was my first anya bast book and i really liked it.',
  'i have looked at some of her other reads but her books seems a little too far fetched for me but to each his own.',
  'what makes this book so different from other menage stories is that the author took the time to really develop her characters.',
  'the men got to know their woman.',
  'they did not claim her and wisk her off and screw like bunnies 24/7.',
  'they took the time to woo her, they loved her, respected her, and they honored her.',
  'i also loved the fact that it was quite ways into the book before they actually had sex.',
  'this was a great read and one i would highly recommend!',
  'i would have loved more action and intrigue but for the most part i loved it.',
  'i hope this books becomes a series.',
  'great job ms. bast.'],
 ["i love reading mini novels and you can't go wrong when it's by jane porter.",
  'yet another great read by this amazingly talented author.',
  'i fell in love with estrella.',
  'she is not only beautiful, but she is strong, compassionate and determined.',
  'carlo is the man you want to hate, but instead end up wishing he was yours.',
  'i enjoyed this book from beginning to end.',
  "not only did the character's personalities draw you in, but the story-line makes you want to reach out and help those that are less fortunate.",
  'i highly recommend this mini novel.',
  "it's a perfect marriage of love, hate, romance and philanthropy."],
 ['this book was extremely incredible to read and it had so much heated passion to describe in every steele relationship.',
  "i'm glad that the brothers and cousin found passionate love at last."],
 ["what's the difference between a guy and a man?",
  'willingness to take a risk on a relationship with a woman.',
  "of course, he's hot, she's hot, and the physical attraction is explosive and enjoyable.",
  'that will earn 3 stars in this genre.',
  'what earned the 4th star is the quality of the characterization and the interaction between the various characters in the book.the book is a quick, short read.',
  "just the right palate pleaser when you want a bit of romance and sex, but don't want to commit."],
 ['gave up about half way through.',
  "too much repetition, too much that didn't make sense and was hard to follow."],
 ["i don't know what i was expecting but this was not it in any way form or fashion.",
  'this book was not exciting at all and i think i ordered the wrong book by accident.'],
 ["i love to read simon wood's books.",
  'this one is morbid and makes the reader and victims skin crawl.',
  'there is not much guessing here.',
  'just outright gruesome.'],
 ['this short story is very confusing.i have no issue with unreliable narrators, but it is difficult to tell what is happening in this story because the writing is too poor for readers to be able to draw any conclusions.',
  'virtually everybody in the story has difficulty relating to others.',
  'conversations begin and then trail off without any important information being related.',
  'the author doesn\'t prevent any "normal" interactions for us to be able to judge if the characters are the ones who have difficult understanding normal human interactions or if the problem actually is with him.',
  'i had assumed that a main character was mentally unbalanced and waiting for that to develop throughout the story.',
  'however, when the story ended, apparently he had become "normal," making a very unfulfilling conclusion.',
  'why set up a "weird" situation for a short story with all this foreshadowing and then leave it unexplored and unexplained?',
  'the only way the author can advance the story is to tell us -- in simple sentences -- what type of people the characters are (things like:  he was a nice person.',
  'he liked people.',
  "he didn't know why, that was just the way he was).",
  "we're never shown anything through the action of the story.",
  "people are just put in situations, have weird, trailing-off conversations, and then we're subjected to basic statements about the type of people that they are.the environment isn't very realistic either.",
  'because of some odd wording, i thought at first that maybe the story was set in another country -- but then a character mentions being from "michigan," which is the only sense of place we got in the story.',
  "we know we're not in michigan and we're in a city.",
  "don't hope for anything more specific.",
  "it's a place where a independent office supply story is still in business (and can afford to pay ten dollars an hour for part time help) -- but is it in modern times?",
  "don't hope for anything specific, because it won't be happening.the characters seem not to know things that we would know.",
  'for example, a character was in "the war" and has returned home and worked another type of job.',
  'later, "old bruises" on his face are thought by other characters to be from "the war."',
  "however, human healing doesn't work that way and all humans should be aware of that.",
  'bruises, even "old" ones, have to be relatively recent and not from old trauma.the experience of reading this story is kind of like if another species was writing about humans and their interactions.',

In [15]:
sentences[0][1]

"he's a famous bounty hunter in oregon in the 1890s who, when he shot the man in the saloon, just finished a years long quest to avenge his sister's murder and is now trying to figure out what to do next."

In [16]:
lemmatizer=WordNetLemmatizer()

In [17]:
len(dataset)

12000

In [18]:
stop_words = set(stopwords.words('english'))

corpus = []

for text in dataset['reviewText']:

    word = re.sub('[^a-zA-Z]', ' ', str(text))
    word = re.sub(r'(http|https|ftp|ssh)://\S+', '', word)
    word = BeautifulSoup(word, 'html.parser').get_text()
    word = word.lower()
    word = word_tokenize(word)

    words = [lemmatizer.lemmatize(w) for w in word if w not in stop_words]

    corpus.append(' '.join(words))

In [19]:
corpus

['jace rankin may short nothing mess man hauled saloon undertaker know famous bounty hunter oregon shot man saloon finished year long quest avenge sister murder trying figure next snotty nosed farm boy rescued gang bully offer money kill man forced ranch reluctantly agrees bring man justice kill outright first need tell sister widower news kyla kyle springer bailey riding trail sleeping ground past month trying find jace want revenge man killed husband took ranch amongst crime keen detour jace want take realizes option hide behind boy persona best try keep pace confrontation along way get shot jace discovers kyle kyla come clean whole reason need scoundrel dead hope still help book share touching moment slow blooming romance kyla find good reason fear men hide behind boy persona watching jace slowly pull shell help conquer fear endearing pain real deeply rooted disappear face sexiness neither understandable aversion marriage magically disappear round nookie would man drifted town town entire adult life man killed fair share men along way feel make good husband father walking wounded unique position help need time realize however packed bursting favorite theme old west setting heroine passing male morally ambiguous hero wounded soul road romance kitchen sink certain distance writing kept getting carried away character distinct fully formed point glaring instance bland telling anything never felt really invested enjoyed quite bit exciting trip watching far away definitely run alongside add hasty tidy ending book left feeling bit less completely satisfied enjoyed book say average still read another book author note read released ebook version noticed lot formatting error missing word mentally edit read sentence make sense bad little distracting',
 'great short read want put read one sitting sex scene great two male one female character bit surprising never thought could learned something new really enjoyed reading book great way get hot bothered take advantage significant',
 'start saying first four book expecting conclude center child alex younger brother argus alex friend sapphire find name bus map find mystery start well written good character development although lot room still quite short book moving onto book swiftly',
 'aggie angela lansbury carry pocketbook instead writing light murder mystery laced misdirection clue lead rather obvious cliche ending setting view described story best believable part aggie well written character light reading',
 'expect type book library pleased find price right',
 'aislinn little girl big dream death older brother decides follow footstep become lady knight quest knighthood brings many challenge temptation forbidden love aislinn learns knight mean putting kingdom front personal concern helping help journey fraught danger filled adventure aislinn forced grow fast must stay strong develop skill necessary realize lifelong dream sword fight passionate love mythical creature courtly game woman honor kind book love idea incorporating real history fantasy m zoltack book based real life story group female knight blending history fiction writing full plot adventure character strong believable grew love cared hardship success aislinn quite main protagonist tenacious bold beautiful strong romance bloom prince well developed year solid friendship teasing enjoyed reading secret courtship idea romance would turn m zoltack twist store shock startle well please conclusion thoroughly recommend book everyone enjoys fantasy romance adventure eagerly awaiting sequel knight glory',
 'making good story unfortunately disappoints tell two alpha member unfriendly pack grown together one gay straight seems get together something happens story told alternating chapter past present story couple fall apart switch time lack sustainable reason break',
 'got like collaborated short story alot time two good writer put head together result turn well case short story writer take age old lesson turn good read begin call crazy picking hitchhiker get graphic little much taste cut nutcase hitchhiking inevitably get together result suspenseful ending felt well deserved account also watched video two author decided break short story idea cool one wrote side scenario scenario without talking tier side going came bring two piece together made fit perfectly think took great talent two author take two seperate story merge well story pretty graphic detail forwarned mind little detail short story definitely pick one',
 'loved book hooked series hope kelsey maxwell really made character get enough',
 'good thing short sweet tease give everything quick kick kick come dark',
 'received copy book review secret society fanatical cult telepathic girl cup tea expected really need another continuational book still read catching fire hunger game get sci fi stuff cup tea sorry',
 'even though already know outcome still enjoyable erotic read little short taste',
 'read review decided give try despite review labeling brutal believe reviewer called brutal beyond disturbing read almost anything recognizing fiction returned less star rating available would used',
 'finished read wicked garden say wow even novella lorelei james write story hot e reader start smokin wicked garden short story lost love reuniting little extra sumthin sumthin billy buchanan return spearfish favor business associate agreed favor also would give chance ignite spark high school flame eden lacroix past ten year regretted walking away eden eden spent last ten year building career dedicated local community center helping risk kid time real relationship occasional string attached hook ups sexy native american rock star jon white feather billy eden see first time ten year chemistry spike chart eden determined fight billy working project could destroy job quickly sweet talk seeing side project thing heat eden billy realizing still strong feeling dunh dunh dunh jon come home couple day billy jon decide want give eden one darkest fantasy boy boy hot menage really like eden even though worried heart billy leaving take charge sexuality scared go want sexually much liked eden story billy jon stole story men sexy strong billy possessive sexy dominant vulnerable absolutely adore way treat eden insecurity display jon oh favorite get wrong love billy way jon treat eden menage melt heart among thing mention jon sexy rock star moon excited jon getting novella ballroom blitz release date folk let tell could get action went work room wicked garden would work room five ten time day wicked garden great novella perfect afternoon want escape hour bonus get see sexy lorelei writes non cowboy yep cowboy hat suit m james know write sexy hell hero',
 'king james version far tell may know kjv published book included get ebook kjv apocrypha kindle bible kjv apocrypha best navigation direct verse jump orking james bible apocryphaorking james bible apocryphafor want read commentary book provided short intro misbach refer either halley bible handbookhalley bible handbook new international version deluxe editionor new unger bible handbookthe new unger bible handbook available kindle ebooks',
 'disappointed book anything blond one figured joke good laugh wrong first count real surprised even joke book second among possible joke least repeated time different part book almost writer kept running list joke heard real concern whether might already recorded decided must least joke finally perfectly frank recall laughing single one joke better described insult mistaking degradation group people humor th grade material bother one worth cent even worth free',
 'super quick book wish would longer really liked character sexy bedroom pool table sex good author',
 'many time author going get amazon delete add comment alleged conspiracy people get f delusional review agree previous reviewer author know basic mechanic writing world written full star page filled grammar problem story suffers problem author inattention detail character inconsistent action like interchangeable peg board author put place need',
 'love j r ward book story completely awsome zsadist favorite series',
 'first author thoroughly enjoyed say concept dragon elf djinn war new there usually truce place elf djinn team eliminate dragon mate attempt wipe dragon race refreshing read story wise mean scarlet pop star hiding year janos dragon also elder scarlet mate janos must protect till impregnate accomplished change thus giving way protect story short page still lot told short space looking forward continuing saga next book',
 'first anya bast book really liked looked read book seems little far fetched make book different menage story author took time really develop character men got know woman claim wisk screw like bunny took time woo loved respected honored also loved fact quite way book actually sex great read one would highly recommend would loved action intrigue part loved hope book becomes series great job m bast',
 'love reading mini novel go wrong jane porter yet another great read amazingly talented author fell love estrella beautiful strong compassionate determined carlo man want hate instead end wishing enjoyed book beginning end character personality draw story line make want reach help less fortunate highly recommend mini novel perfect marriage love hate romance philanthropy',
 'book extremely incredible read much heated passion describe every steele relationship glad brother cousin found passionate love last',
 'difference guy man willingness take risk relationship woman course hot hot physical attraction explosive enjoyable earn star genre earned th star quality characterization interaction various character book book quick short read right palate pleaser want bit romance sex want commit',
 'gave half way much repetition much make sense hard follow',
 'know expecting way form fashion book exciting think ordered wrong book accident',
 'love read simon wood book one morbid make reader victim skin crawl much guessing outright gruesome',
 'short story confusing issue unreliable narrator difficult tell happening story writing poor reader able draw conclusion virtually everybody story difficulty relating others conversation begin trail without important information related author prevent normal interaction u able judge character one difficult understanding normal human interaction problem actually assumed main character mentally unbalanced waiting develop throughout story however story ended apparently become normal making unfulfilling conclusion set weird situation short story foreshadowing leave unexplored unexplained way author advance story tell u simple sentence type people character thing like nice person liked people know way never shown anything action story people put situation weird trailing conversation subjected basic statement type people environment realistic either odd wording thought first maybe story set another country character mention michigan sense place got story know michigan city hope anything specific place independent office supply story still business afford pay ten dollar hour part time help modern time hope anything specific happening character seem know thing would know example character war returned home worked another type job later old bruise face thought character war however human healing work way human aware bruise even old one relatively recent old trauma experience reading story kind like another specie writing human interaction know act way elephant interaction might make sense proofreading better earlier review stated going guess issue corrected still professional job',
 'found book enjoyable read first chapter really take keep entertained end enjoyed much immediately purchased next two book series',
 'amy parker going hawaii week christmas business give sex relationship focus career justin garrett traveling companion associate law firm work together definitely plane boldly masturbates seat next supposedly napping hears everything make hard left trip accidentally found racy email friend laptop know want know deepest darkest desire plan something hawaii meet client mitch magruder justin apprenticed going current job mitch justin share friendly camaraderie justin know count mitch help fulfill amy fantasy two work get amy relax unwind justin get relax enough give heart unwrapped jaci burton paint vivid picture two men coaxing amy letting go letting seduce reader enjoy molten hot eacute nage scene exquisite feeling finally intimate someone fantasized year m burton book power packed emotion sensuality love style creates believable intelligent character unwrapped suck page one keep riveted end highly recommended kiss pepper f eacute nage anal sex lindyreviewer twolips review llc',
 'jodi birthday last place want stuck working bos boyfriend insists night job completed little choice jodi bos may mattress dancing decided early would string attached relationship lately jodi second thought relationship mark sound really good thing get interesting jodi get busted breaking entering sinfully sexy man mark rodriguez merge security company old buddy sam favor ask sam first mark would like sam join fulfilling jodi eacute nage fantasy birthday surprise however mark start second thought see jodi sam together perhaps mark want jodi string well private property spicy erotic novella eacute nage quite birthday surprise jodi mark jodi sam heat thing lusty novel like mark immediately reconsidering idea eacute nage relationship nothing like seeing woman getting another man make realize serious private property leave thinking breaking entering might bad thing mirandafor joyfully reviewed',
 'interesting historic value really story rather accounting event interesting biographical information st person',
 'book detailed interesting felt time character much erotic got bored place tired savannah get book especially free good read',
 'rd book second time still good exciting loving story sharing making sacrifice love life easy',
 'type love ghost story enjoy book however someone else may enjoy never let people opinion put trying book look interesting said kind story',
 'believe listed romance read romance novel looking something uplifting book dark depressing find story writing bad depressing sex high overview go depth developement character relationship spoiler alert like happy ending forget said review guess strongly enough truly understand hopefully say plainly enough others expectation waste time hero dy brutal death saving heroine book continues several chapter showing remaining character pick life go end heroine sitting porch contemplating life wondering lie ahead man love gone almost cry end anger wasted free time reading book',
 'read book twice make sure happy thought knew short book bought actually felt bad finsihed story line great charcters well thought however wish longer less rush get book finished',
 'awesomee thriller hitched beginning dragged along roller coaster ride way end book great twist turn fell inlove main character girlfriend highly recommend',
 'ok story thought character little shallow pull brought together way fast booked moved sexy end blink felt like chapter get point maybe story taken place literally one place felt like really room growth story ended however well written term format would give another book author read',
 'great twist turning mystery plot unable stop reading end definitely must read mystery suspense reader definitely recommend',
 'think series first type story see james bond based bulldog drummond',
 'book wrong many level although usually type spoiler one hope daughter one scientist lab wolfe held although mark refuse mate age lab burn wolfe believed dead year hope alone unable move another man bond hope evil mother apparently know wolfe survived sending photo hope men fake course wolfe appears nowhere capture hope punishes teasing sex allowing orgasm due mating heat apparently writhing pain continues try getting answer seek find nothing wrong get worse first time stick as finally decides innocent want relieve might rough animal surface course begs orgasm forgiven joking mother show quick falling sandbag thing take joke writing even good sex attempt story thrown',
 'story written badly struck emotionally tone deaf fiction abuse whether physical emotional take u place difficult place unfamiliar maybe sadly familiar story found thinking people act way think way thing little pat little rushed language bit careless observation little bit hard specify exactly seemed story almost reading collection story written somebody much exposure father child dynamic watching lifetime movie marathon',
 'another light hearted novel hard put henry wright delightful character get tight spot',
 'never read author thoroughly enjoyed story would gladly read another disfigured hero fear pain pride wonderfully described felt wanting reach gently touch scar reassure exactly time aidan touched warwick get wrong warwick brutally strong hot male character privy thought within story began get protective feeling aidan acquired saw extremely handsome man warwick really passion romace well mixed much strengh wit character sometimes sure real hero story everyone like strong take matter hand heroine definately book one woman rescue squad perfect match mysterious masked hired guard warwick sex hot wicked well enjoy',
 'book deserving winner prestigious giller prize wanting read time wanted read boyden first book three day road first good book one even better good read three day road first precursor one helped understand character bit like three day road book difficult read way keep waiting terrible cataclysmic thing happen even though know going happen make less terrible book also similar three day road told viewpoint two different people young niece annie terrible story tell heals sharing highly recommend book would suggest read three day road first feel richer experience enjoying superlative story telling book take everyday life magical world seems real reading',
 'amazon curse built relationship event developed vampire bride showalter book stand alone much better know back story rating would different already connected character reading previous book vampire bride focus layel king vampire delilah amazon warrior however introduced many character including zane nola happy find story ended would suggest using book alone introduction showalter writing missing',
 'fan bound heart series perhaps best review book try two since reader romantic book see much romance sharing',
 'stop reading series love character jacob especially victor relationship well plot always good bit mystery going adventure get know victor past voice usual something look forward',
 'loved series seeing story family member together convenient best',
 'like dragon free download gave try aside needing editing least proofreading clear clunky storytelling found disappointed story start slow work unevenly burst action end conclusion blue jump premise dragonseer saga series halfway download half turned preview first full length dragoneers book even knowing prequel even knowing novella hoped complete self contained tale amounted overlong prologue bother preview novella accurate indicator author style sense story already know dragonseer saga reading list anytime soon',

In [20]:
len(corpus)

12000

In [21]:
X_train,X_test,y_train,y_test=train_test_split(
    corpus,dataset['sentiment'],test_size=0.20,random_state=42
)

In [22]:
X_train

['looking forward book came double space every paragraph kindle edition since action move around formatting make story hard follow die hard like want bother sad thing good book spoiled formatting fault author story good book energy read also emailed author',
 'already owned book spouse forgot already part library book unfortunate amazon safeguard place notify book already library',
 'cool forgot request rate came make mine unreliable rating doubt change rotation planet enough measure',
 'short short story basically scene party one night though admittedly entire book taken period one pure erotica hea real relationship depth sexual description really disappointed get used kindle notation find lack page number confusing really know getting load found regency romance really idea men love look took min read wish could return even felt ripped',
 'secret service agent secrests even longer service meet argus ward former secret service agent run protection agency catering rich famous secret functioning paranoid schizophrenic accused killing famous client also richest man america argus find memory murder psychiatric ward prove world get diagnosed paranoid schizophrenic real paranoia right eric christopherson debut novel psychological thriller twist turn paranoid real easily blur reality line cracked christopherson masterful description paranoid schizophrenic would like tell real episode certain point sure argus ward cracked sure sane cycle went end mood twist turn pick one plan reading mr christopherson',
 'world diana love alma rude nice day rude kiss leaf go london still thinking sleep mistress everyday diana come london argue meet mistress alma still sleep mistress wanting diana stop realizes another man might ask marry diana decides want marry omg self centered man whore ever read sleep around supposed feeling heroine stand author make sad heroine written love man like would never feeling would never married sleeping around thing alone like give sex woman love good gosh liked book george alonna got together book rushing end get',
 'funny end author gave preview next book garbage collector hope come toss book',
 'much happens location teaser rich playboy fall model go missing possibly foul play get dunno felt like might develop murder mystery supposed beginning book definitely stand alone story even though free think people end deleting',
 'gratuitous violence much imagination fortunately quick read patience finish book',
 'nice romance two mature adult short point predictable would like background two character even daughter real character development feel drawn character good quick read glad free got',
 'dang gage freaking hot sweet need find mr tool look love great hot book romance',
 'charlene harris start hot heavy jungle let heat humidity forth coming change felt reader entrance dynamic hero black leopard sexy man etc place burden heroine almost stiffling conclusion know arrival thrill',
 'book really humor usually dry kept laughing doubt book everyone said offer sound advice prospective reader download book free premise first entry laughing least smiling stop reading also check pulse',
 'perhaps surreal little story absolutely set ever encountered truly surreal silly',
 'loved book definite keeper rafe really loved wife cathy love especially evident pivotal moment leaf rafe decision whether proceed forward go back safe wife dee knight superb job describing tornado scene new found fear respect tornado',
 'heroine mother award annoying heroine mother story good poorly written heroine whined time heroine family well way talked showed heroine bad mouth teacher showed manner sometimes time acted like came froma gutter hero reserved ten year ago wanted get rid heroine said dated make jealous enjoyed date book deserve one star plot good heroine heroine mother ruined',
 'love historical fantasy seeing short story really get well read wonderful',
 'writing atrocious book one kindle would thrown across room addition constant repetition word sentence structure often bad made little sense',
 'plot idea interesting poorly executed character unrealistic underdeveloped kept reading though skimmed good deal find ended revealed preposterous frankly insulting like author bothered writing better book',
 'awhile thought going something special wrong even year lover still get enough sex go without seeing nothing one else matter unless together supposed love conquers sex masquerading love conquers two need one together always becomes sex writer theme concept fails develop could erotica except writer introduces much story separate couple want parted team past could present evidence change occurred world could adapt could information going world required return promise reader could understand mission perhaps see one well given anything work developed enough make sense even fantasy world character remain physically year grow intelligence understanding world around sex fulfilling moment must constantly repeated without loss passion perception alone may needed else elder seem nothing mythical god pleased long forever time people life meaning writer share reader trite hackneyed devoid substance',
 'explain know might think star rating would equal c star book one truly exceptional think deserves c see sci fi book lucy suddenly find beamed outer space quickly embarks relationship three actually human lost memory trying return home mind amount sex book elsborg writes erotica well book nice hot lucy thought also hilarious great see change impact alien culture also opinion author write right amount plot sufficient detail categorize author erotic author said need plot sex personally feel little cheated money get book look like erotica one two sex scene filled plot good think actually good balance two star never went back read barbara elsborg book read read read mostly short snow play power love think really short story well also novel tend longer side warning spoiler story lucy three relationship however also mm sex book although involve three',
 'sure wish book carried x rating movie read first page deleted fourth f word several page along reference body part yeah know rate book complete someone give review warn others thrive gutter language handle book like stuart wood sexual reference need four letter word frequency book offer expected interesting story line reformed jewel thief perhaps warm love interest',
 'even story even know start begin end minute well least free',
 'believe review book read year ago really enjoy new kind concept reviewed year ago would able give thorough enthusiastic review think people give shot enjoy genre',
 'bought samhain website coupon rwa conference extremely impressed first reading author thought fantastic job short story fact amazon looking something else read saw book star rating shocked writing review review done good job recounting plot say think story well written dark steamy nicely executed hea stumbled little bit black moment enough throw story sound intriguing give shot wonderful writer',
 'well written could hardly put would love read family struggle happiness',
 'book fairly well written pace solid enjoyed character looking forward reading next book',
 'seemed tea party wet dream horrible thing unionist read liberal take fema camp come life',
 'woman discovers father want marry objectionable man becomes objectionable future groom find perfect man ruin wade warrick come line roguish brother belief discreet agreeable plan wade surprised helen request mean rake sympathy plight admires pluck lead passionate romance like sense humor pragmatic little idealistic helen brave girl charting destiny loyal trustworthy wade share trait fine little romance',
 'short erotic story science fiction flair kind wish character development seemed choppy time',
 'first must reiterate warning title samhain pub mean sexually explicit forewarned beckett de saxby cousin colin christiana friend throughout childhood beckett return war far different man young one christiana idolized hardened cold often spends night woman loose moral drunk understand hear band marauder hounding people countryside around without something christiana grown beauty tried keep thought losing fight promotes household making maid furious attacked take care personally warns serious consequence something happens think lust beginning always loved beckett prospective bride arrives mother brother tow thing get interesting christiana heartbroken gamely continues kidnapped knight black armor rescue thankful timely interruption kiss black knight cheek jealous kiss beckett pull away christiana thinking might given black knight something else asked watch beckett fall passionately love christiana servant ending one missed highly recommended',
 'keely jack gel appear chemistry keely always strident harsh care relationship individually fun character book together fit',
 'great pleasant read enjoyed every work book also want mention excellent formatting book read kindle check bonus end book f scott fitzgerald influence film tv adaptation famous quote f scott fitzgerald recommend book',
 'soul lose good introduction first book soul screamer series necessary read soul take recommended book tell u story kaylee life mental institution admitted certain incident mall bestfriend emma easily sympathized easily loved emma supportive friend curious one character book though lydia mysterious yet seems know kaylee secret person institute understand curious happened helped kaylee would great know next book though short easy read book give u glimpse kaylee life know truth behind called panic attack able understand better answer question might read first book series hope take time read novella say anything want give anything away may spoil future reading good enjoyable recommend think best read start soul take nevertheless still start series read afterwards',
 'story good one many many editing error great deal inconsistency character liked concept kept getting bogged',
 'cover fit perfect know time instruction remove replace kindle dx remove shipped back along kindle want damage unit feel getting replacement kindle dx compensated small price cover would advise amazon include removal instruction want change cover done always happy business amazon aaboulet',
 'ok would great story much raunchy sex make people buy book sex sell culture',
 'yes storyline good short piece writing consistancy horrible glad free would hated paid crap neadless say buying reading anymore author',
 'short felt like bad snapshot excerpt intended real story taking kindle',
 'downloaded kindle knowing expect sounded like interesting book really ended enjoying book lot classic fantasy tale lot humor woven throughout wistril apprentice kern live castle kauph general want left alone study three story wistril meant three story included wistril besieged wistril afloat wistril betrothed story wistril show brain always triumph brawn come humorous solution rather difficult situation thoroughly enjoyed story wistril pretentious yet caring hilarious wizard constantly surprise reader crazy solution problem kern competent apprentice weave ton hilarious sarcasm throughout novel wistril sworn white wizard never harm magic add interesting twist thing tuttle readable writing style really enjoyed develops wonderfully quirky character story really classic kind tongue cheek dungeon crawling humor pleasantly surprised amused overall absolutely loved book immediately went online got couple tuttle kindle book love classic fantasy humorous twist check book',
 'book say south hot mess idea potential never fully realized character flat fleshed hard time giving damn either way book dialogue little real narration thing kind dog spike katherine sniveling mess good deal time part sex scene sex scene better written laurel k hamilton sex scene least bonus end fight seemed anti climatic predictable really wish idea character fleshed end hard time getting thru glad gotten free',
 'carly successful computer expert built great business healthy nest egg looking much needed break carly buy property middle wyoming move away hustle bustle california dmitri life safely beneath ground several century death property owner living heir dmitri bargain property sold carly start see strange man dream excited encouraging dream dream way becoming reality carly soon realise meet dmitri belakov person find really phantom desire delicious short story one lover vampire sure enjoy reviewing book monster review',
 'terrible might good actual story instead couple chapter end even end awful read author',
 'another story misidentification confusion everyone finally get everything straight end well people involved okay',
 'one better first contact concentrated story fighting gripe tesh dar prequel series keep getting told mighty tesh dar got tired repetition quickly fine author want change mythos prequels guess prerogative feel wrong reader still remembers three book undoes logic therefore suspension disbelief tesh dar walk wall send space get cave even taking account year older first three book feel like make sense anymore going finish series bought really feel like prequel series worthy first three book really wish prequel series tesh dar life brought point killing reza first found',
 'spoiler h fat girl class still bitter never asked h return town thinner ready rub h face lasted chapter maybe really enjoyed author previous work looking forward thought would story reluctant h remorseful h woo h back love since never happened sure book title h carrying box h giving kitten really wooing sex reacts like total jerk done instead apologizing give lame line unforgivable going ask forgive locked jail cell listen sheriff guess even thought acted needed get knee beg forgiveness really showing remorse instead acting high handed continually doubt compare h action ex wife h intervenes daughter h immediate response told referring secret h shared h regarding daughter let go later book also question honesty regarding major event last straw one character burned therefore forever continue think worse woman h included never believed best h really ever work h love instead h continually took granted h disappointing throughout book stand h long enough give lip service lay doormat end unbelievably annoying even read last two page yes two page go could h show continually treating h like crap hurting one paragraph fine well next time life go way somehow h fault sure agree well time step someone else wanted easy convenient romance make book huge disappointment especially talented author',
 'another old classic amazon released ebook format read story first fifty year ago held hardback binding library book conjunction twenty thousand league sea search castaway discovered exciting jules verne writing truly started reading book could find certainty appreciated every one saw mysterious island ebook format amazon simply copy desire acquire book read book personal hard copy library ebook format even though grown reading hardback paperback book enjoying smell printer ink experiencing feeling good binding fine paper hand longer able collect original format due lack available shelf space discovered able carry book around kindle fire hd bad way go hunting book shelf book shelf novel digging box box book place storage book completely taking home looking right book unfortunately become unrealistic however regress review jules verne book mysterious island read believe love',
 'despite corny feel game gay chicken book definitely worth read read maybe even third hot two guy together also attraction feel forced thought flowed perfectly fakkit probably read fourth time',
 'loved reading story first reader would think brock good true middle book find self cheering happy family sad story ended wanted badly know happens next three looking heart warming story must',
 'used advice yet bound come handy sooner later glad downloaded way need',
 'cute short story meant light hearted fun would recommend anyone interested manage bdsm',
 'like story really good read afternoon character realistic villain rotten enough make exciting reading author work future',
 'finished delver magic book sanctum breach part really enjoyed toward end became involved nearly missed bus stop thing however kept first mr inlo must taken eye sword one point three human woman book still called lauren rachel guess nearly missed bus stop another problem book probably personal problem became little agravated really getting one plot line sudden jumped another one know area covered sometimes little disjointed next three book know enjoy well',
 'although one main character emotionally challenged enjoy book storyline found quick easy read',
 'started well okay started okay already knew lying get go sure lied age come able tell come across maturity year old time lied everything else lied hurtful basically telling shared anything yeah glad able set life child without dependant upon anything think carried torch though ever really getting close anyone else year however seem mind keeping type relationship labeled year trying replace maybe probably author wanted reader believe rate yet fall short really irked fact soon threatend press getting involved low behold time reporter could care less woman let alone whether secret love child told press oh yeah try come hurt party trying right charlie yet really lost tell side story year old virgin hooked year old playboy dumped getting pregnant oh yeah even bigger question hot commodity come bodyguard protecting charlie gina would kidnapper would make fast buck',
 'virgin read like written novice beginner properly researched wearing wimple began early middle age certainly judea time nun retained medieval dress including wimple vatican ii shortly thereafter beginning seemed right got silly read keep thought pretty good thought try another since recommendation really know people could give sophomoric novel star rating different people respond work different way thought interesting premise drawn marian theme catholicism mysticism general ridiculous plot downloaded novel seemed interesting try see work improved update although think much novel another reviewer mentioned good repairman jack series really read three fourth good probably better crime suspense series nice surprise really excellent highly recommended offering really reasonable price fed paying upwards kindle thriller try series',
 'author blow away start think novel thrill come across one story writing style pacing way lead care much character god eye completely different kind book loved one much need read author work immediately',
 'book enjoyable nothing outstanding want escape fantasy land good book probably read',
 'belkin neoprene cover slip cover look lot expensive cost durable roughed slim fit kindle dx great stuff luggage carry briefcase computer case travel light enough carried dx',
 'really impressed story short enough background character need depth',
 'got two page giving style clunky internal monolog gel character know story start end chase scene probably would really interesting author bothered write',
 'read lot independent author publish amazon generally mind book quite expected book really really sorry wasted idea premise book bad one actual execution story whole different matter dialogue childish stilted read like high school drama main character year old come high school buffy wan na good editing work could good story waste money',
 'good read always find romance happening office nice wanted find ended make wish office romance turned way',
 'ever blind wonder author partially blind thought fear joy author writes realistic especially time park paul faith christina due brain aneurysm blind eye time operation made possible see one eye remember vividly standing middle busy sidewalk freaking mentally see know son gone book good drawback like bed scene scene kathleen woman forgot name thought unnecessary hope author writes book',

In [23]:
y_train

9182     1
11091    0
6428     1
288      0
2626     1
        ..
11964    0
5191     1
5390     0
860      0
7270     1
Name: sentiment, Length: 9600, dtype: int64

In [24]:
len(X_train)

9600

In [25]:
# Applying Bow,TfIdf, Word2Vec

bow=CountVectorizer()
tfidf=TfidfVectorizer()

In [26]:
model=Word2Vec(sentences=corpus)

In [27]:
X_train_bow=bow.fit_transform(X_train)
X_test_bow=bow.transform(X_test)

In [28]:
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)

In [29]:
tokenized_corpus = [doc.split() for doc in corpus]

In [30]:
tokenized_corpus

[['jace',
  'rankin',
  'may',
  'short',
  'nothing',
  'mess',
  'man',
  'hauled',
  'saloon',
  'undertaker',
  'know',
  'famous',
  'bounty',
  'hunter',
  'oregon',
  'shot',
  'man',
  'saloon',
  'finished',
  'year',
  'long',
  'quest',
  'avenge',
  'sister',
  'murder',
  'trying',
  'figure',
  'next',
  'snotty',
  'nosed',
  'farm',
  'boy',
  'rescued',
  'gang',
  'bully',
  'offer',
  'money',
  'kill',
  'man',
  'forced',
  'ranch',
  'reluctantly',
  'agrees',
  'bring',
  'man',
  'justice',
  'kill',
  'outright',
  'first',
  'need',
  'tell',
  'sister',
  'widower',
  'news',
  'kyla',
  'kyle',
  'springer',
  'bailey',
  'riding',
  'trail',
  'sleeping',
  'ground',
  'past',
  'month',
  'trying',
  'find',
  'jace',
  'want',
  'revenge',
  'man',
  'killed',
  'husband',
  'took',
  'ranch',
  'amongst',
  'crime',
  'keen',
  'detour',
  'jace',
  'want',
  'take',
  'realizes',
  'option',
  'hide',
  'behind',
  'boy',
  'persona',
  'best',
  'try',
  'keep',
  'pace',
  'confrontation',
  'along',
  'way',
  'get',
  'shot',
  'jace',
  'discovers',
  'kyle',
  'kyla',
  'come',
  'clean',
  'whole',
  'reason',
  'need',
  'scoundrel',
  'dead',
  'hope',
  'still',
  'help',
  'book',
  'share',
  'touching',
  'moment',
  'slow',
  'blooming',
  'romance',
  'kyla',
  'find',
  'good',
  'reason',
  'fear',
  'men',
  'hide',
  'behind',
  'boy',
  'persona',
  'watching',
  'jace',
  'slowly',
  'pull',
  'shell',
  'help',
  'conquer',
  'fear',
  'endearing',
  'pain',
  'real',
  'deeply',
  'rooted',
  'disappear',
  'face',
  'sexiness',
  'neither',
  'understandable',
  'aversion',
  'marriage',
  'magically',
  'disappear',
  'round',
  'nookie',
  'would',
  'man',
  'drifted',
  'town',
  'town',
  'entire',
  'adult',
  'life',
  'man',
  'killed',
  'fair',
  'share',
  'men',
  'along',
  'way',
  'feel',
  'make',
  'good',
  'husband',
  'father',
  'walking',
  'wounded',
  'unique',
  'position',
  'help',
  'need',
  'time',
  'realize',
  'however',
  'packed',
  'bursting',
  'favorite',
  'theme',
  'old',
  'west',
  'setting',
  'heroine',
  'passing',
  'male',
  'morally',
  'ambiguous',
  'hero',
  'wounded',
  'soul',
  'road',
  'romance',
  'kitchen',
  'sink',
  'certain',
  'distance',
  'writing',
  'kept',
  'getting',
  'carried',
  'away',
  'character',
  'distinct',
  'fully',
  'formed',
  'point',
  'glaring',
  'instance',
  'bland',
  'telling',
  'anything',
  'never',
  'felt',
  'really',
  'invested',
  'enjoyed',
  'quite',
  'bit',
  'exciting',
  'trip',
  'watching',
  'far',
  'away',
  'definitely',
  'run',
  'alongside',
  'add',
  'hasty',
  'tidy',
  'ending',
  'book',
  'left',
  'feeling',
  'bit',
  'less',
  'completely',
  'satisfied',
  'enjoyed',
  'book',
  'say',
  'average',
  'still',
  'read',
  'another',
  'book',
  'author',
  'note',
  'read',
  'released',
  'ebook',
  'version',
  'noticed',
  'lot',
  'formatting',
  'error',
  'missing',
  'word',
  'mentally',
  'edit',
  'read',
  'sentence',
  'make',
  'sense',
  'bad',
  'little',
  'distracting'],
 ['great',
  'short',
  'read',
  'want',
  'put',
  'read',
  'one',
  'sitting',
  'sex',
  'scene',
  'great',
  'two',
  'male',
  'one',
  'female',
  'character',
  'bit',
  'surprising',
  'never',
  'thought',
  'could',
  'learned',
  'something',
  'new',
  'really',
  'enjoyed',
  'reading',
  'book',
  'great',
  'way',
  'get',
  'hot',
  'bothered',
  'take',
  'advantage',
  'significant'],
 ['start',
  'saying',
  'first',
  'four',
  'book',
  'expecting',
  'conclude',
  'center',
  'child',
  'alex',
  'younger',
  'brother',
  'argus',
  'alex',
  'friend',
  'sapphire',
  'find',
  'name',
  'bus',
  'map',
  'find',
  'mystery',
  'start',
  'well',
  'written',
  'good',
  'character',
  'development',
  'although',
  'lot',
  'room',
  'still',
  'quite',
  'short',
  'book',
  'moving',
  'onto',
  'book',
  'swiftly'],
 ['aggie',
  'angela',
  'lansbury',
  'carry',
  'pocketbook',
  'instead',
  'writing',
  'light',
  'murder',
  'mystery',
  'laced',
  'misdirection',
  'clue',
  'lead',
  'rather',
  'obvious',
  'cliche',
  'ending',
  'setting',
  'view',
  'described',
  'story',
  'best',
  'believable',
  'part',
  'aggie',
  'well',
  'written',
  'character',
  'light',
  'reading'],
 ['expect', 'type', 'book', 'library', 'pleased', 'find', 'price', 'right'],
 ['aislinn',
  'little',
  'girl',
  'big',
  'dream',
  'death',
  'older',
  'brother',
  'decides',
  'follow',
  'footstep',
  'become',
  'lady',
  'knight',
  'quest',
  'knighthood',
  'brings',
  'many',
  'challenge',
  'temptation',
  'forbidden',
  'love',
  'aislinn',
  'learns',
  'knight',
  'mean',
  'putting',
  'kingdom',
  'front',
  'personal',
  'concern',
  'helping',
  'help',
  'journey',
  'fraught',
  'danger',
  'filled',
  'adventure',
  'aislinn',
  'forced',
  'grow',
  'fast',
  'must',
  'stay',
  'strong',
  'develop',
  'skill',
  'necessary',
  'realize',
  'lifelong',
  'dream',
  'sword',
  'fight',
  'passionate',
  'love',
  'mythical',
  'creature',
  'courtly',
  'game',
  'woman',
  'honor',
  'kind',
  'book',
  'love',
  'idea',
  'incorporating',
  'real',
  'history',
  'fantasy',
  'm',
  'zoltack',
  'book',
  'based',
  'real',
  'life',
  'story',
  'group',
  'female',
  'knight',
  'blending',
  'history',
  'fiction',
  'writing',
  'full',
  'plot',
  'adventure',
  'character',
  'strong',
  'believable',
  'grew',
  'love',
  'cared',
  'hardship',
  'success',
  'aislinn',
  'quite',
  'main',
  'protagonist',
  'tenacious',
  'bold',
  'beautiful',
  'strong',
  'romance',
  'bloom',
  'prince',
  'well',
  'developed',
  'year',
  'solid',
  'friendship',
  'teasing',
  'enjoyed',
  'reading',
  'secret',
  'courtship',
  'idea',
  'romance',
  'would',
  'turn',
  'm',
  'zoltack',
  'twist',
  'store',
  'shock',
  'startle',
  'well',
  'please',
  'conclusion',
  'thoroughly',
  'recommend',
  'book',
  'everyone',
  'enjoys',
  'fantasy',
  'romance',
  'adventure',
  'eagerly',
  'awaiting',
  'sequel',
  'knight',
  'glory'],
 ['making',
  'good',
  'story',
  'unfortunately',
  'disappoints',
  'tell',
  'two',
  'alpha',
  'member',
  'unfriendly',
  'pack',
  'grown',
  'together',
  'one',
  'gay',
  'straight',
  'seems',
  'get',
  'together',
  'something',
  'happens',
  'story',
  'told',
  'alternating',
  'chapter',
  'past',
  'present',
  'story',
  'couple',
  'fall',
  'apart',
  'switch',
  'time',
  'lack',
  'sustainable',
  'reason',
  'break'],
 ['got',
  'like',
  'collaborated',
  'short',
  'story',
  'alot',
  'time',
  'two',
  'good',
  'writer',
  'put',
  'head',
  'together',
  'result',
  'turn',
  'well',
  'case',
  'short',
  'story',
  'writer',
  'take',
  'age',
  'old',
  'lesson',
  'turn',
  'good',
  'read',
  'begin',
  'call',
  'crazy',
  'picking',
  'hitchhiker',
  'get',
  'graphic',
  'little',
  'much',
  'taste',
  'cut',
  'nutcase',
  'hitchhiking',
  'inevitably',
  'get',
  'together',
  'result',
  'suspenseful',
  'ending',
  'felt',
  'well',
  'deserved',
  'account',
  'also',
  'watched',
  'video',
  'two',
  'author',
  'decided',
  'break',
  'short',
  'story',
  'idea',
  'cool',
  'one',
  'wrote',
  'side',
  'scenario',
  'scenario',
  'without',
  'talking',
  'tier',
  'side',
  'going',
  'came',
  'bring',
  'two',
  'piece',
  'together',
  'made',
  'fit',
  'perfectly',
  'think',
  'took',
  'great',
  'talent',
  'two',
  'author',
  'take',
  'two',
  'seperate',
  'story',
  'merge',
  'well',
  'story',
  'pretty',
  'graphic',
  'detail',
  'forwarned',
  'mind',
  'little',
  'detail',
  'short',
  'story',
  'definitely',
  'pick',
  'one'],
 ['loved',
  'book',
  'hooked',
  'series',
  'hope',
  'kelsey',
  'maxwell',
  'really',
  'made',
  'character',
  'get',
  'enough'],
 ['good',
  'thing',
  'short',
  'sweet',
  'tease',
  'give',
  'everything',
  'quick',
  'kick',
  'kick',
  'come',
  'dark'],
 ['received',
  'copy',
  'book',
  'review',
  'secret',
  'society',
  'fanatical',
  'cult',
  'telepathic',
  'girl',
  'cup',
  'tea',
  'expected',
  'really',
  'need',
  'another',
  'continuational',
  'book',
  'still',
  'read',
  'catching',
  'fire',
  'hunger',
  'game',
  'get',
  'sci',
  'fi',
  'stuff',
  'cup',
  'tea',
  'sorry'],
 ['even',
  'though',
  'already',
  'know',
  'outcome',
  'still',
  'enjoyable',
  'erotic',
  'read',
  'little',
  'short',
  'taste'],
 ['read',
  'review',
  'decided',
  'give',
  'try',
  'despite',
  'review',
  'labeling',
  'brutal',
  'believe',
  'reviewer',
  'called',
  'brutal',
  'beyond',
  'disturbing',
  'read',
  'almost',
  'anything',
  'recognizing',
  'fiction',
  'returned',
  'less',
  'star',
  'rating',
  'available',
  'would',
  'used'],
 ['finished',
  'read',
  'wicked',
  'garden',
  'say',
  'wow',
  'even',
  'novella',
  'lorelei',
  'james',
  'write',
  'story',
  'hot',
  'e',
  'reader',
  'start',
  'smokin',
  'wicked',
  'garden',
  'short',
  'story',
  'lost',
  'love',
  'reuniting',
  'little',
  'extra',
  'sumthin',
  'sumthin',
  'billy',
  'buchanan',
  'return',
  'spearfish',
  'favor',
  'business',
  'associate',
  'agreed',
  'favor',
  'also',
  'would',
  'give',
  'chance',
  'ignite',
  'spark',
  'high',
  'school',
  'flame',
  'eden',
  'lacroix',
  'past',
  'ten',
  'year',
  'regretted',
  'walking',
  'away',
  'eden',
  'eden',
  'spent',
  'last',
  'ten',
  'year',
  'building',
  'career',
  'dedicated',
  'local',
  'community',
  'center',
  'helping',
  'risk',
  'kid',
  'time',
  'real',
  'relationship',
  'occasional',
  'string',
  'attached',
  'hook',
  'ups',
  'sexy',
  'native',
  'american',
  'rock',
  'star',
  'jon',
  'white',
  'feather',
  'billy',
  'eden',
  'see',
  'first',
  'time',
  'ten',
  'year',
  'chemistry',
  'spike',
  'chart',
  'eden',
  'determined',
  'fight',
  'billy',
  'working',
  'project',
  'could',
  'destroy',
  'job',
  'quickly',
  'sweet',
  'talk',
  'seeing',
  'side',
  'project',
  'thing',
  'heat',
  'eden',
  'billy',
  'realizing',
  'still',
  'strong',
  'feeling',
  'dunh',
  'dunh',
  'dunh',
  'jon',
  'come',
  'home',
  'couple',
  'day',
  'billy',
  'jon',
  'decide',
  'want',
  'give',
  'eden',
  'one',
  'darkest',
  'fantasy',
  'boy',
  'boy',
  'hot',
  'menage',
  'really',
  'like',
  'eden',
  'even',
  'though',
  'worried',
  'heart',
  'billy',
  'leaving',
  'take',
  'charge',
  'sexuality',
  'scared',
  'go',
  'want',
  'sexually',
  'much',
  'liked',
  'eden',
  'story',
  'billy',
  'jon',
  'stole',
  'story',
  'men',
  'sexy',
  'strong',
  'billy',
  'possessive',
  'sexy',
  'dominant',
  'vulnerable',
  'absolutely',
  'adore',
  'way',
  'treat',
  'eden',
  'insecurity',
  'display',
  'jon',
  'oh',
  'favorite',
  'get',
  'wrong',
  'love',
  'billy',
  'way',
  'jon',
  'treat',
  'eden',
  'menage',
  'melt',
  'heart',
  'among',
  'thing',
  'mention',
  'jon',
  'sexy',
  'rock',
  'star',
  'moon',
  'excited',
  'jon',
  'getting',
  'novella',
  'ballroom',
  'blitz',
  'release',
  'date',
  'folk',
  'let',
  'tell',
  'could',
  'get',
  'action',
  'went',
  'work',
  'room',
  'wicked',
  'garden',
  'would',
  'work',
  'room',
  'five',
  'ten',
  'time',
  'day',
  'wicked',
  'garden',
  'great',
  'novella',
  'perfect',
  'afternoon',
  'want',
  'escape',
  'hour',
  'bonus',
  'get',
  'see',
  'sexy',
  'lorelei',
  'writes',
  'non',
  'cowboy',
  'yep',
  'cowboy',
  'hat',
  'suit',
  'm',
  'james',
  'know',
  'write',
  'sexy',
  'hell',
  'hero'],
 ['king',
  'james',
  'version',
  'far',
  'tell',
  'may',
  'know',
  'kjv',
  'published',
  'book',
  'included',
  'get',
  'ebook',
  'kjv',
  'apocrypha',
  'kindle',
  'bible',
  'kjv',
  'apocrypha',
  'best',
  'navigation',
  'direct',
  'verse',
  'jump',
  'orking',
  'james',
  'bible',
  'apocryphaorking',
  'james',
  'bible',
  'apocryphafor',
  'want',
  'read',
  'commentary',
  'book',
  'provided',
  'short',
  'intro',
  'misbach',
  'refer',
  'either',
  'halley',
  'bible',
  'handbookhalley',
  'bible',
  'handbook',
  'new',
  'international',
  'version',
  'deluxe',
  'editionor',
  'new',
  'unger',
  'bible',
  'handbookthe',
  'new',
  'unger',
  'bible',
  'handbook',
  'available',
  'kindle',
  'ebooks'],
 ['disappointed',
  'book',
  'anything',
  'blond',
  'one',
  'figured',
  'joke',
  'good',
  'laugh',
  'wrong',
  'first',
  'count',
  'real',
  'surprised',
  'even',
  'joke',
  'book',
  'second',
  'among',
  'possible',
  'joke',
  'least',
  'repeated',
  'time',
  'different',
  'part',
  'book',
  'almost',
  'writer',
  'kept',
  'running',
  'list',
  'joke',
  'heard',
  'real',
  'concern',
  'whether',
  'might',
  'already',
  'recorded',
  'decided',
  'must',
  'least',
  'joke',
  'finally',
  'perfectly',
  'frank',
  'recall',
  'laughing',
  'single',
  'one',
  'joke',
  'better',
  'described',
  'insult',
  'mistaking',
  'degradation',
  'group',
  'people',
  'humor',
  'th',
  'grade',
  'material',
  'bother',
  'one',
  'worth',
  'cent',
  'even',
  'worth',
  'free'],
 ['super',
  'quick',
  'book',
  'wish',
  'would',
  'longer',
  'really',
  'liked',
  'character',
  'sexy',
  'bedroom',
  'pool',
  'table',
  'sex',
  'good',
  'author'],
 ['many',
  'time',
  'author',
  'going',
  'get',
  'amazon',
  'delete',
  'add',
  'comment',
  'alleged',
  'conspiracy',
  'people',
  'get',
  'f',
  'delusional',
  'review',
  'agree',
  'previous',
  'reviewer',
  'author',
  'know',
  'basic',
  'mechanic',
  'writing',
  'world',
  'written',
  'full',
  'star',
  'page',
  'filled',
  'grammar',
  'problem',
  'story',
  'suffers',
  'problem',
  'author',
  'inattention',
  'detail',
  'character',
  'inconsistent',
  'action',
  'like',
  'interchangeable',
  'peg',
  'board',
  'author',
  'put',
  'place',
  'need'],
 ['love',
  'j',
  'r',
  'ward',
  'book',
  'story',
  'completely',
  'awsome',
  'zsadist',
  'favorite',
  'series'],
 ['first',
  'author',
  'thoroughly',
  'enjoyed',
  'say',
  'concept',
  'dragon',
  'elf',
  'djinn',
  'war',
  'new',
  'there',
  'usually',
  'truce',
  'place',
  'elf',
  'djinn',
  'team',
  'eliminate',
  'dragon',
  'mate',
  'attempt',
  'wipe',
  'dragon',
  'race',
  'refreshing',
  'read',
  'story',
  'wise',
  'mean',
  'scarlet',
  'pop',
  'star',
  'hiding',
  'year',
  'janos',
  'dragon',
  'also',
  'elder',
  'scarlet',
  'mate',
  'janos',
  'must',
  'protect',
  'till',
  'impregnate',
  'accomplished',
  'change',
  'thus',
  'giving',
  'way',
  'protect',
  'story',
  'short',
  'page',
  'still',
  'lot',
  'told',
  'short',
  'space',
  'looking',
  'forward',
  'continuing',
  'saga',
  'next',
  'book'],
 ['first',
  'anya',
  'bast',
  'book',
  'really',
  'liked',
  'looked',
  'read',
  'book',
  'seems',
  'little',
  'far',
  'fetched',
  'make',
  'book',
  'different',
  'menage',
  'story',
  'author',
  'took',
  'time',
  'really',
  'develop',
  'character',
  'men',
  'got',
  'know',
  'woman',
  'claim',
  'wisk',
  'screw',
  'like',
  'bunny',
  'took',
  'time',
  'woo',
  'loved',
  'respected',
  'honored',
  'also',
  'loved',
  'fact',
  'quite',
  'way',
  'book',
  'actually',
  'sex',
  'great',
  'read',
  'one',
  'would',
  'highly',
  'recommend',
  'would',
  'loved',
  'action',
  'intrigue',
  'part',
  'loved',
  'hope',
  'book',
  'becomes',
  'series',
  'great',
  'job',
  'm',
  'bast'],
 ['love',
  'reading',
  'mini',
  'novel',
  'go',
  'wrong',
  'jane',
  'porter',
  'yet',
  'another',
  'great',
  'read',
  'amazingly',
  'talented',
  'author',
  'fell',
  'love',
  'estrella',
  'beautiful',
  'strong',
  'compassionate',
  'determined',
  'carlo',
  'man',
  'want',
  'hate',
  'instead',
  'end',
  'wishing',
  'enjoyed',
  'book',
  'beginning',
  'end',
  'character',
  'personality',
  'draw',
  'story',
  'line',
  'make',
  'want',
  'reach',
  'help',
  'less',
  'fortunate',
  'highly',
  'recommend',
  'mini',
  'novel',
  'perfect',
  'marriage',
  'love',
  'hate',
  'romance',
  'philanthropy'],
 ['book',
  'extremely',
  'incredible',
  'read',
  'much',
  'heated',
  'passion',
  'describe',
  'every',
  'steele',
  'relationship',
  'glad',
  'brother',
  'cousin',
  'found',
  'passionate',
  'love',
  'last'],
 ['difference',
  'guy',
  'man',
  'willingness',
  'take',
  'risk',
  'relationship',
  'woman',
  'course',
  'hot',
  'hot',
  'physical',
  'attraction',
  'explosive',
  'enjoyable',
  'earn',
  'star',
  'genre',
  'earned',
  'th',
  'star',
  'quality',
  'characterization',
  'interaction',
  'various',
  'character',
  'book',
  'book',
  'quick',
  'short',
  'read',
  'right',
  'palate',
  'pleaser',
  'want',
  'bit',
  'romance',
  'sex',
  'want',
  'commit'],
 ['gave',
  'half',
  'way',
  'much',
  'repetition',
  'much',
  'make',
  'sense',
  'hard',
  'follow'],
 ['know',
  'expecting',
  'way',
  'form',
  'fashion',
  'book',
  'exciting',
  'think',
  'ordered',
  'wrong',
  'book',
  'accident'],
 ['love',
  'read',
  'simon',
  'wood',
  'book',
  'one',
  'morbid',
  'make',
  'reader',
  'victim',
  'skin',
  'crawl',
  'much',
  'guessing',
  'outright',
  'gruesome'],
 ['short',
  'story',
  'confusing',
  'issue',
  'unreliable',
  'narrator',
  'difficult',
  'tell',
  'happening',
  'story',
  'writing',
  'poor',
  'reader',
  'able',
  'draw',
  'conclusion',
  'virtually',
  'everybody',
  'story',
  'difficulty',
  'relating',
  'others',
  'conversation',
  'begin',
  'trail',
  'without',
  'important',
  'information',
  'related',
  'author',
  'prevent',
  'normal',
  'interaction',
  'u',
  'able',
  'judge',
  'character',
  'one',
  'difficult',
  'understanding',
  'normal',
  'human',
  'interaction',
  'problem',
  'actually',
  'assumed',
  'main',
  'character',
  'mentally',
  'unbalanced',
  'waiting',
  'develop',
  'throughout',
  'story',
  'however',
  'story',
  'ended',
  'apparently',
  'become',
  'normal',
  'making',
  'unfulfilling',
  'conclusion',
  'set',
  'weird',
  'situation',
  'short',
  'story',
  'foreshadowing',
  'leave',
  'unexplored',
  'unexplained',
  'way',
  'author',
  'advance',
  'story',
  'tell',
  'u',
  'simple',
  'sentence',
  'type',
  'people',
  'character',
  'thing',
  'like',
  'nice',
  'person',
  'liked',
  'people',
  'know',
  'way',
  'never',
  'shown',
  'anything',
  'action',
  'story',
  'people',
  'put',
  'situation',
  'weird',
  'trailing',
  'conversation',
  'subjected',
  'basic',
  'statement',
  'type',
  'people',
  'environment',
  'realistic',
  'either',
  'odd',
  'wording',
  'thought',
  'first',
  'maybe',
  'story',
  'set',
  'another',
  'country',
  'character',
  'mention',
  'michigan',
  'sense',
  'place',
  'got',
  'story',
  'know',
  'michigan',
  'city',
  'hope',
  'anything',
  'specific',
  'place',
  'independent',
  'office',
  'supply',
  'story',
  'still',
  'business',
  'afford',
  'pay',
  'ten',
  'dollar',
  'hour',
  'part',
  'time',
  'help',
  'modern',
  'time',
  'hope',
  'anything',
  'specific',
  'happening',
  'character',
  'seem',
  'know',
  'thing',
  'would',
  'know',
  'example',
  'character',
  'war',
  'returned',
  'home',
  'worked',
  'another',
  'type',
  'job',
  'later',
  'old',
  'bruise',
  'face',
  'thought',
  'character',
  'war',
  'however',
  'human',
  'healing',
  'work',
  'way',
  'human',
  'aware',
  'bruise',
  'even',
  'old',
  'one',
  'relatively',
  'recent',
  'old',
  'trauma',
  'experience',
  'reading',
  'story',
  'kind',
  'like',
  'another',
  'specie',
  'writing',
  'human',
  'interaction',
  'know',
  'act',
  'way',
  'elephant',
  'interaction',
  'might',
  'make',
  'sense',

In [31]:
def document_vector(doc):
    words = doc.split()
    word_vectors = []

    for word in words:
        if word in model.wv:
            word_vectors.append(model.wv[word])

    if len(word_vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(word_vectors, axis=0)

In [32]:
X_train_avgword2vec = np.array([document_vector(doc) for doc in X_train])
X_test_avgword2vec = np.array([document_vector(doc) for doc in X_test])

In [33]:
X_test_avgword2vec

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2400, 100))

In [34]:
from tqdm.auto import tqdm


def train_model(model, X_train, y_train, X_test, y_test, params):

    print(f'\n---------------------------{model.__class__.__name__}---------------------------')

    cv = GridSearchCV(
        estimator=model,
        param_grid=params,
        cv=5,
        scoring='accuracy',
        n_jobs=-1,
        verbose=1   # shows internal CV progress
    )

    cv.fit(X_train, y_train)

    y_predicted = cv.predict(X_test)

    accuracy = accuracy_score(y_true=y_test, y_pred=y_predicted)
    cr = classification_report(y_true=y_test, y_pred=y_predicted)

    print('Best Params:', cv.best_params_)
    print('Accuracy:', accuracy)
    print(cr)

In [39]:
randomforest=RandomForestClassifier()
naive_bayes=MultinomialNB()
decisionTree=DecisionTreeClassifier()
xgb=XGBClassifier()

rf_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'max_features': ['sqrt', 'log2']
#
}

nb_params = {
    'alpha': [0.1, 0.5, 1.0, 5.0, 10.0],
    # 'fit_prior': [True, False]
}

dt_params = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    # 'max_depth': [None, 10, 20, 30, 50],
    # 'min_samples_split': [2, 5, 10],
    # 'min_samples_leaf': [1, 2, 4],
    # 'max_features': [None, 'sqrt', 'log2']
}

xgb_params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    # 'learning_rate': [0.01, 0.1, 0.2],
    # 'subsample': [0.7, 0.8, 1.0],
    # 'colsample_bytree': [0.7, 0.8, 1.0],
    # 'gamma': [0, 0.1, 0.3]
}

In [46]:
models=[randomforest]
params=[rf_params]
trainings=[X_train_bow,X_train_tfidf]
testing=[X_test_bow,X_test_tfidf]

In [48]:
from tqdm.auto import tqdm


def train_all_model():

    total_iterations = len(models) * len(trainings)

    with tqdm(total=total_iterations, desc="Training Progress") as pbar:

        for i in range(len(models)):
            for j in range(len(trainings)):

                train_model(
                    model=models[i],
                    X_train=trainings[j],
                    y_train=y_train,
                    X_test=testing[j],
                    y_test=y_test,
                    params=params[i]
                )

                pbar.update(1)

In [49]:
train_all_model()

Training Progress:   0%|          | 0/2 [00:00<?, ?it/s]

---------------------------RandomForestClassifier---------------------------
Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best Params: {'max_depth': None, 'n_estimators': 300}
Accuracy: 0.8158333333333333
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1190
           1       0.82      0.81      0.82      1210

    accuracy                           0.82      2400
   macro avg       0.82      0.82      0.82      2400
weighted avg       0.82      0.82      0.82      2400


---------------------------RandomForestClassifier---------------------------
Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best Params: {'max_depth': None, 'n_estimators': 200}
Accuracy: 0.8058333333333333
              precision    recall  f1-score   support

           0       0.79      0.82      0.81      1190
           1       0.82      0.79      0.80      1210

    accuracy                           0.81      2400
   macro avg       0.81      0.81      0.81      2400
weighted avg       0.81      0.81      0.81      2400